# Generated by Django 4.0.4 on 2022-07-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('CROSSOVER', 'Crossover'), ('HATCHBACK', 'Hatchback')], max_length=100, verbose_name='Car Type')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Model')),
                ('price', models.IntegerField(default=10000, verbose_name='Car price')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'Car models',
                'ordering': ['-created_at', 'car_type'],
            },
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(null=True, verbose_name='Customer balance')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Customer email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80, verbose_name='Showroom name')),
                ('location', django_countries.fields.CountryField(max_length=2, verbose_name='Location')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Showroom balance')),
                ('cars', models.ManyToManyField(blank=True, to='showroom.car')),
                ('customers', models.ManyToManyField(blank=True, to='showroom.customer')),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Supplier name')),
                ('foundation_year', models.DateField(verbose_name='Year of foundation')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('cars', models.ManyToManyField(blank=True, to='showroom.car')),
                ('showrooms', models.ManyToManyField(blank=True, to='showroom.showroom')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='showroom.carmanufacturer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.customer')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carmanufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.customer')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carmanufacturer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.carmanufacturer'),
        ),
    ]
