version: '3.9'

services:
  web:
    container_name: pythonapp
    image: pythonapp
    build: .
    command: bash -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_NAME=show_room_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=show_room_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  redis:
    image: redis

  celery:
      build: .
      command: celery -A main worker -l info
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      volumes:
        - .:/app
      depends_on:
        - redis
        - web

  celery-beat:
      build: .
      command: celery -A main beat -l info
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      volumes:
        - .:/app
      depends_on:
        - web
        - redis

  flower:
      image: mher/flower:0.9.5
      command: ['flower', '--broker=redis://redis:6379', '--port=5555']
      ports:
        - 5555:5555
      depends_on:
        - redis
        - celery-beat

volumes:
  postgres_data: